# Generated by Django 3.1.4 on 2021-03-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='food_database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_Location', models.CharField(max_length=100)),
                ('Enter_The_Name_Of_Organization', models.CharField(max_length=1000)),
                ('Enter_Address', models.CharField(max_length=1000)),
                ('Enter_Food_Menu', models.CharField(max_length=1000)),
                ('Enter_Quantity_Per_Person', models.CharField(max_length=1000)),
                ('Time_To_Pickup_Range_With_Date', models.CharField(max_length=1000)),
            ],
        ),
    ]
